# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiVersion 1.0.0
@api {POST} api/v1/call/answer Answer Call
@apiGroup Call
@apiParam {String} reciver_id user id comma seprated array
@apiParam {String} is_accept 0/1
@apiUse default_headers
@apiErrorExample {json} Error-Response / HTTP 404 Not Found
{
                    "payload": null,
                    "message": "Validation success",
                    "result": true
                }
###
