# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiVersion 1.0.0
@api {POST} api/v1/chat Send Chat Message
@apiGroup Chat
@apiParam {Number} receiver_id Message Receiver ID
@apiParam {String} [message] Message
@apiParam {File} [image] Image
@apiUse default_headers
###
# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiVersion 1.0.0
@api {POST} api/v1/chat/read Chat Read
@apiGroup Chat
@apiParam {Number} chat_room_id Chat Room ID
@apiUse default_headers
###
# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiVersion 1.0.0
@api {GET} api/v1/chat/users Chat User List
@apiGroup Chat
@apiUse default_headers
###
# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiVersion 1.0.0
@api {GET} api/v1/chat/list Chat List
@apiGroup Chat
@apiParam {Number} chat_room_id Chat Room ID
@apiParam {Number} page Page Number
@apiUse default_headers
###
# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiVersion 1.0.0
@api {POST} api/v1/chat/report Add Chat Report
@apiGroup Chat
@apiParam {Number} reported_user User ID
@apiParam {String} reason Reason for Report
@apiParam {String} comments Explaination
@apiUse default_headers
###
# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiVersion 1.0.0
@api {POST} api/v1/chat/block Block Chat User
@apiGroup Chat
@apiParam {Number} block_user_id Block User ID
@apiParam {Number} block_status Block Status 0 or 1
@apiUse default_headers
###
# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiVersion 1.0.0
@api {POST} api/v1/chat/settings Update Chat Settings
@apiGroup Chat
@apiParam {Number} online_status Online Status 0 or 1
@apiParam {Number} read_receipts Read Receipts 0 or 1
@apiUse default_headers
###
# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiVersion 1.0.0
@api {DELETE} api/v1/chat Delete Chat Message
@apiGroup Chat
@apiParam {Number} chat_id Chat Message ID
@apiUse default_headers
###
