# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiVersion 1.0.0
@api {POST} api/v1/contact-us send mail
@apiGroup Contact Us
@apiParam {String} message User message
@apiParam {String} [name] User Name
@apiParam {String} [email] User Email
@apiParam {String} [country_code] User Phone Code
@apiParam {String} [phone] User Phone Number
@apiUse default_headers
@apiSuccessExample {json} Success-Response / HTTP 200 OK
{
                "payload": null,
                "message": "We have received your message.",
                "result": true
            }
###
