# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiDescription Get Profile Details for match
@apiVersion 1.0.0
@api {GET} api/v1/home Home
@apiGroup HomeAPI
@apiParam {String} [page] Page Number
@apiParam {String} [gender] Male, Female, Non-binary, All
@apiParam {String} [relationship_type] Relationship, Keeping it casual, Friendship, Figuring out my relationship goals
@apiParam {String} [dating_preference] Male, Female, Non-binary, All
@apiParam {Number} [min_age] Min age
@apiParam {Number} [max_age] Max age
@apiParam {Number} [min_distance] Min distance
@apiParam {Number} [max_distance] Max distance
@apiParam {String} [latitude] Latitude
@apiParam {String} [longitude] Longitude
@apiParam {String} [like_to_have_more_childran] yes or no
@apiUse default_headers
###
# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiDescription Accept Profile
@apiVersion 1.0.0
@api {POST} api/v1/home/accept Accept Profile
@apiGroup HomeAPI
@apiParam {String} preferred_user_id Accept Profile ID
@apiUse default_headers
###
# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiDescription Get Match Profile
@apiVersion 1.0.0
@api {GET} api/v1/match-all Get Match Profile
@apiGroup HomeAPI
@apiUse default_headers
###
# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiDescription unmatch Profile
@apiVersion 1.0.0
@api {POST} api/v1/unmatch Unmatch Profile
@apiGroup HomeAPI
@apiParam {String} preferred_user_id User Profile ID
@apiUse default_headers
###
