# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiDescription Get currently logged in user's profile
@apiVersion 1.0.0
@api {GET} api/v1/profile My Profile
@apiGroup Profile
@apiUse default_headers
###
# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiVersion 1.0.0
@api {PUT} api/v1/profile Update My Profile
@apiGroup Profile
@apiParam {String} first_name First name
@apiParam {String} [last_name] Last name
@apiParam {String} email Email
@apiParam {String} [phone] Phone
@apiUse default_headers
###
# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiVersion 1.0.0
@api {POST} api/v1/avatar Update My Avatar
@apiGroup Profile
@apiParam {File} image Image
@apiUse default_headers
###
# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiVersion 1.0.0
@api {POST} api/v1/profile/setup01 Profile Setup01
@apiGroup Profile
@apiParam {String} name Name
@apiParam {String} last_name Last name
@apiParam {String} gender Male, Female, Non-binary, Custom
@apiParam {String} want_email_notify yes or no
@apiParam {Number} age Age
@apiParam {String} location Location
@apiParam {String} latitude Latitude
@apiParam {String} longitude Longitude
@apiUse default_headers
###
# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiVersion 1.0.0
@api {POST} api/v1/profile/setup02 Profile Setup Video
@apiGroup Profile
@apiParam {String} file file
@apiUse default_headers
###
# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiVersion 1.0.0
@api {POST} api/v1/profile/setupImages Profile Setup Images
@apiGroup Profile
@apiParam {Array} images File Collection
@apiUse default_headers
###
# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiVersion 1.0.0
@api {POST} api/v1/profile/setup03 Profile Setup03
@apiGroup Profile
@apiParam {String} interests comma separated
@apiParam {String} occupation Occupation
@apiParam {String} hometown Hometown
@apiParam {Number} height Height
@apiParam {String} nationality Nationality
@apiUse default_headers
###
# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiVersion 1.0.0
@api {POST} api/v1/profile/setup04 Profile Setup04
@apiGroup Profile
@apiParam {String} relationship_type Relationship, Keeping it casual, Friendship, Figuring out my relationship goals
@apiParam {String} dating_intentions Male, Female, Non-binary, All
@apiParam {Number} min_age optional
@apiParam {Number} max_age optional
@apiParam {String} [like_to_have_more_childran] yes or no
@apiUse default_headers
###
# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiVersion 1.0.0
@api {GET} api/v1/profile/support Get Interest and Nationality
@apiGroup Profile
@apiUse default_headers
###
# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiVersion 1.0.0
@api {POST} api/v1/profile/complete Profile Complete
@apiGroup Profile
@apiUse default_headers
###
# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiVersion 1.0.0
@api {GET} api/v1/profile/show Get Profile Details
@apiGroup Profile
@apiParam {String} user_id User ID
@apiUse default_headers
###
# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiVersion 1.0.0
@api {DELETE} api/v1/profile Delete My Account
@apiGroup Profile
@apiUse default_headers
###
