# ******************************************************** #
#           AUTO-GENERATED. DO NOT EDIT THIS FILE.         #
# ******************************************************** #
#    Create your files in `resources/docs/apidoc/manual`   #
# ******************************************************** #
###
@apiVersion 1.0.0
@api {GET} api/v1/call/token Genrate Token
@apiGroup Token
@apiParam {String} reciver_id user id
@apiParam {String} call_type audio/video
@apiUse default_headers
@apiErrorExample {json} Error-Response / HTTP 404 Not Found
{
                    "payload": null,
                    "message": "Validation success",
                    "result": true
                }
###
